### ISSUE TITLE
콜백주소를 라우터로 변환

### ISSUE THREAD

**Issue by bjrambo** [rhymix/rhymix-sociallogin#8]
일부 로그인을 지원해주는 곳에서 callback 주소에 ? 및 &을 붙여서 callback 주소를 허용하는 사태가 점점 줄어들고 있고, 해당 주소를 점점 깐깐하게 진행되어가고 있습니다.

라우터를 이용하여 다음과 같은 주소로 callback url을 설정하여 동작하도록 변경합니다.

```
https://domain.com/sociallogin/sociallogin/callback/{$service}
```
e.g)
```
https://domain.com/sociallogin/sociallogin/callback/apple
https://domain.com/sociallogin/sociallogin/callback/discord
https://domain.com/sociallogin/sociallogin/callback/tiktok
```

**Comment by kijin** [comment]
URL에 `sociallogin`이 2번 들어갔어요. 모듈 내부의 route에 모듈명을 반복해서 쓸 필요는 없습니다.

**Comment by bjrambo** [comment]
https://github.com/rhymix/rhymix-sociallogin/commit/99ba845b319415f0aba8279be1a9de7d7d7b2946
